import os

SECRET_KEY = os.urandom(24)

# DEBUG = True

DB_USERNAME = 'root'
DB_PASSWORD = 'password'
DB_HOST = '127.0.0.1'
DB_PORT = '3306'
DB_NAME = 'bbs2'

# PERMANENT_SESSION_LIFETIME =

DB_URI = 'mysql+pymysql://%s:%s@%s:%s/%s?charset=utf8' % (DB_USERNAME,DB_PASSWORD,DB_HOST,DB_PORT,DB_NAME)

SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = False

CURRENT_USER_ID = 'asdfsa'

MAIL_SERVER = 'smtp.163.com'
MAIL_PORT = '25'
MAIL_USE_SSL = False
MAIL_USE_STL = False
MAIL_USERNAME = '15832217331@163.com'
MAIL_PASSWORD = 'python1023'
MAIL_DEFAULT_SENDER = '15832217331@163.com'


MEMCACHED_PORT = ['127.0.0.1:11211']