"""empty message

Revision ID: 05a4c2ace82a
Revises: a1deeb665292
Create Date: 2019-03-18 11:28:21.665545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05a4c2ace82a'
down_revision = 'a1deeb665292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.drop_column('post', 'creat_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('creat_time', mysql.DATETIME(), nullable=True))
    op.drop_column('post', 'create_time')
    # ### end Alembic commands ###
