"""empty message

Revision ID: 0f5e519ce0c9
Revises: aa2d382c33ef
Create Date: 2019-03-20 22:34:14.265429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f5e519ce0c9'
down_revision = 'aa2d382c33ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('front_user', 'avatar',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=150),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('front_user', 'avatar',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
