"""empty message

Revision ID: 3d58d96e3d79
Revises: 120d082e4e46
Create Date: 2019-01-30 16:11:02.726768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d58d96e3d79'
down_revision = '120d082e4e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_role', sa.Column('authority', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'cms_role', ['name'])
    op.drop_column('cms_role', 'authorities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_role', sa.Column('authorities', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cms_role', type_='unique')
    op.drop_column('cms_role', 'authority')
    # ### end Alembic commands ###
