"""empty message

Revision ID: 45ff7bb683a8
Revises: 1d1b89033255
Create Date: 2019-03-16 16:05:05.803034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ff7bb683a8'
down_revision = '1d1b89033255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('desc', sa.String(length=99), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'desc')
    # ### end Alembic commands ###
