"""empty message

Revision ID: 9ab7bac13d97
Revises: ee42f0d55a59
Create Date: 2019-03-16 00:30:51.021472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ab7bac13d97'
down_revision = 'ee42f0d55a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cms_user', 'email',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('cms_user', 'phone',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cms_user', 'phone',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
    op.alter_column('cms_user', 'email',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###
