"""empty message

Revision ID: a1deeb665292
Revises: 45ff7bb683a8
Create Date: 2019-03-18 11:18:32.438787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1deeb665292'
down_revision = '45ff7bb683a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('name', sa.String(length=20), nullable=False))
    op.drop_column('front_user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('username', mysql.VARCHAR(length=20), nullable=False))
    op.drop_column('front_user', 'name')
    # ### end Alembic commands ###
