"""empty message

Revision ID: a2ea7a69ba61
Revises: 0f5e519ce0c9
Create Date: 2019-03-21 15:39:30.708847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ea7a69ba61'
down_revision = '0f5e519ce0c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operate_time', sa.DateTime(), nullable=True),
    sa.Column('operator_id', sa.String(length=25), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['front_user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sticky_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operate_time', sa.DateTime(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['cms_user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sticky_record')
    op.drop_table('like_record')
    # ### end Alembic commands ###
