"""empty message

Revision ID: d6ab6477e461
Revises: 93d6666bdfa6
Create Date: 2019-03-03 15:00:34.228127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6ab6477e461'
down_revision = '93d6666bdfa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('mobile', sa.String(length=15), nullable=False))
    op.drop_index('phone', table_name='front_user')
    op.create_unique_constraint(None, 'front_user', ['mobile'])
    op.drop_column('front_user', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('phone', mysql.VARCHAR(length=15), nullable=False))
    op.drop_constraint(None, 'front_user', type_='unique')
    op.create_index('phone', 'front_user', ['phone'], unique=True)
    op.drop_column('front_user', 'mobile')
    # ### end Alembic commands ###
