"""empty message

Revision ID: ee42f0d55a59
Revises: 28f0bcf2f4d7
Create Date: 2019-03-13 13:37:10.826652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee42f0d55a59'
down_revision = '28f0bcf2f4d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'priority')
    # ### end Alembic commands ###
