"""empty message

Revision ID: f863e611b1aa
Revises: 5be466d1f3e8
Create Date: 2019-01-25 10:49:33.358788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f863e611b1aa'
down_revision = '5be466d1f3e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('join_time', sa.DateTime(), nullable=True))
    op.add_column('cms_user', sa.Column('email', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'cms_user', ['email'])
    op.drop_column('cms_user', 'jointime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('jointime', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'cms_user', type_='unique')
    op.drop_column('cms_user', 'email')
    op.drop_column('cms_user', 'join_time')
    # ### end Alembic commands ###
